BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repositories.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();

            return View(objCompanyList);
        }
        public IActionResult Upsert(int? CompanyId) //update,insert
        {
            if (CompanyId == null || CompanyId == 0)
            {
                //insert
                return View(new Company());
            }
            else
            {
                //update
                Company companyObj = _unitOfWork.Company.Get(i => i.Id == CompanyId);
                return View(companyObj);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Company companyObj)
        {
            if (ModelState.IsValid)
            {   
                //0 mean new item, then create one
                if(companyObj.Id == 0) 
                {
                    _unitOfWork.Company.Add(companyObj);
                }
                else
                {
                //update item
                    _unitOfWork.Company.Update(companyObj);
                }

                _unitOfWork.Save();
                TempData["success"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(companyObj);
            }
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();

            return Json(new { data = objCompanyList });
        }

        [HttpDelete]
        public IActionResult Delete(int? companyId)
        {
            var CompanyToBeDeleted = _unitOfWork.Company.Get(u => u.Id== companyId);
            if(CompanyToBeDeleted == null)
            {
                return Json(new { success = false, message="Error while deleting" });
            }

            _unitOfWork.Company.Remove(CompanyToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = false, message = "Delete Successful" });
        }
        #endregion
    }
}

BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repositories.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using Stripe;
using Product = BulkyBook.Models.Product;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return View(objProductList);
        }
        public IActionResult Upsert(int? productId) //update,insert
        {
            IEnumerable<SelectListItem> CategoryList = _unitOfWork.Category.
            GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            ProductVM productVM = new()
            {
                CategoryList = CategoryList,
                Product = new Product()
            };

            //ViewBag.CategoryList = CategoryList; //method1
            //ViewData["CategoryList"] = CategoryList; //method 2


            if (productId == null || productId == 0)
            {
                //insert
                return View(productVM);
            }
            else
            {
                //update
                productVM.Product = _unitOfWork.Product.Get(i => i.Id == productId, includeProperties: "ProductImages");
                return View(productVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, List<IFormFile>? files)
        {
            if (ModelState.IsValid)
            {
                //0 mean new item, then create one
                if (productVM.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);
                }
                else
                {
                    //update item
                    _unitOfWork.Product.Update(productVM.Product);
                }

                _unitOfWork.Save();

                //save image file to wwwroot / images / product
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach (IFormFile file in files)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        string productPath = @"images\products\product-" + productVM.Product.Id;
                        string finalPath = Path.Combine(wwwRootPath, productPath);

                        //create a new productImage folder for this product if folder not exist
                        if (!Directory.Exists(finalPath))
                        {
                            Directory.CreateDirectory(finalPath);
                        }

                        //start copy the file to finalPath[ProductImages folder]
                        using (var fileStream = new FileStream(Path.Combine(finalPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }

                        ProductImage productImage = new()
                        {
                            ImageUrl = @"\" + productPath + "/" + fileName,
                            ProductId = productVM.Product.Id
                        };

                        if (productVM.Product.ProductImages == null)
                        {
                            productVM.Product.ProductImages = new List<ProductImage>();
                        }

                        productVM.Product.ProductImages.Add(productImage);
                    }

                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();
                }

                TempData["success"] = "Product created/updated successfully";
                return RedirectToAction("Index");
            }
            else
            {

                //refill the Category Selection List 
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });

                //If not valid return to view itself
                return View(productVM);
            }
        }

        public IActionResult DeleteImage(int imageId)
        {
            var ImageToBeDeleted = _unitOfWork.ProductImage.Get(u => u.Id == imageId);
            int productId = ImageToBeDeleted.ProductId;

            if (ImageToBeDeleted != null)
            {
                if (!string.IsNullOrEmpty(ImageToBeDeleted.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath,
                                       ImageToBeDeleted.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
            }

            _unitOfWork.ProductImage.Remove(ImageToBeDeleted);
            _unitOfWork.Save();

            TempData["success"] = "Image Deleted Successfully!";

            return RedirectToAction(nameof(Upsert), new { productId = productId });
        }

        //no need anymore since using UpSert
        //public IActionResult Edit(int? productId)
        //{
        //    if (productId == null || productId == 0)
        //    {
        //        return NotFound();
        //    }

        //    Product? productFromDb = _unitOfWork.Product.Get(u => u.Id == productId); //find() only work with primary key

        //    if (productFromDb == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(productFromDb);
        //}

        //[HttpPost]
        //public IActionResult Edit(Product obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _unitOfWork.Product.Update(obj);
        //        _unitOfWork.Save();
        //        TempData["success"] = "Product updated successfully";
        //        return RedirectToAction("Index");
        //    }

        //    return View();
        //}

        //public IActionResult Delete(int? productId)
        //{
        //    if (productId == null || productId == 0)
        //    {
        //        return NotFound();
        //    }

        //    Product? productFromDb = _unitOfWork.Product.Get(u => u.Id == productId);

        //    if (productFromDb == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(productFromDb);
        //}

        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeletePOST(int? productId)
        //{
        //    Product? obj = _unitOfWork.Product.Get(u => u.Id == productId);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }
        //    _unitOfWork.Product.Remove(obj);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Product delete successfully";
        //    return RedirectToAction("Index");
        //}

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return Json(new { data = objProductList });
        }

        [HttpDelete]
        public IActionResult Delete(int? productId)
        {
            var productToBeDeleted = _unitOfWork.Product.Get(u => u.Id == productId);
            if (productToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            string productPath = @"images\products\product-" + productId;
            string finalPath = Path.Combine(_webHostEnvironment.WebRootPath, productPath);

            if (Directory.Exists(finalPath))
            {
                //get all file path and delete it from the folder one by one
                string[] filePaths = Directory.GetFiles(finalPath);
                foreach (string filePath in filePaths)
                {
                    System.IO.File.Delete(filePath);
                }

                //delete folder
                Directory.Delete(finalPath);
            }

            _unitOfWork.Product.Remove(productToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = false, message = "Delete Successful" });
        }
        #endregion
    }
}

BulkyWeb/Areas/Admin/Views/Company/Delete.cshtml
@model Product
<form method="post">
    <div class="border p-3 my-4">
        <input asp-for="Id" type="hidden" />
        <div class="row pb-2">
            <h2 class="text-primary"> Edit Product</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Title" class="p-0"></label>
            <input asp-for="Title" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <textarea asp-for="Description" disabled class="form-control"></textarea>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ISBN" class="p-0"></label>
            <input asp-for="ISBN" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Author" class="p-0"></label>
            <input asp-for="Author" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ListPrice" class="p-0"></label>
            <input asp-for="ListPrice" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Price" class="p-0"></label>
            <input asp-for="Price" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Price50" class="p-0"></label>
            <input asp-for="Price50" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Price100" class="p-0"></label>
            <input asp-for="Price100" disabled class="form-control" />
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button class="btn btn-primary form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Product" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

BulkyWeb/Areas/Admin/Views/Company/Edit.cshtml
@model Product
<form method="post">
    <div class="border p-3 my-4">
        <input asp-for="Id" type="hidden" />
        <div class="row pb-2">
            <h2 class="text-primary"> Edit Product</h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All"></div> *@ @* this will show all error message *@
        <div asp-validation-summary="ModelOnly"></div> @* this will only show the error message that without properties. *@
        <div class="mb-3 row p-1">
            <label asp-for="Title" class="p-0"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Description" class="p-0"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div> 
        <div class="mb-3 row p-1">
            <label asp-for="ISBN" class="p-0"></label>
            <input asp-for="ISBN" class="form-control" />
            <span asp-validation-for="ISBN" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Author" class="p-0"></label>
            <input asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ListPrice" class="p-0"></label>
            <input asp-for="ListPrice" class="form-control" />
            <span asp-validation-for="ListPrice" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Price" class="p-0"></label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Price50" class="p-0"></label>
            <input asp-for="Price50" class="form-control" />
            <span asp-validation-for="Price50" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Price100" class="p-0"></label>
            <input asp-for="Price100" class="form-control" />
            <span asp-validation-for="Price100" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Product" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>


@* adding this line of code will implement client side validation, but custom validation will still go into server side *@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Company List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-square"></i>
                Create New Company
            </a>
        </div>
    </div>


    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Phone Number</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/company.js"></script>
}

BulkyWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<form method="post" enctype="multipart/form-data">
    <input asp-for="Id" hidden />
    <div class="border p-3 my-4">
        <div class="row pb-2">
            @* change label, according to action[update/create] *@
            <h2 class="text-primary"> @(Model.Id != 0 ? "Update" : "Create") Company</h2>
            <hr />
        </div>
        <div class="row">
            <div class="col-12">
                @* <div asp-validation-summary="All"></div> *@ @* this will show all error message *@
                <div asp-validation-summary="ModelOnly"></div> @* this will only show the error message that without properties. *@
                <div class="mb-3 row p-1">
                    <label asp-for="Name" class="p-0"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3 row p  -1">
                    <label asp-for="PhoneNumber" class="p-0"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="StreetAddress" class="p-0"></label>
                    <input asp-for="StreetAddress" class="form-control" />
                    <span asp-validation-for="StreetAddress" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="City" class="p-0"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="State" class="p-0"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="PostalCode" class="p-0"></label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                @if (Model.Id != 0)
                {
                    <button class="btn btn-primary form-control">Update</button>
                }
                else
                {
                    <button class="btn btn-primary form-control">Create</button>
                }
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Company" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>


@* adding this line of code will implement client side validation, but custom validation will still go into server side *@
@section Scripts {
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'ai tinycomments mentions anchor autolink charmap codesample emoticons lists table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed permanentpen footnotes advtemplate advtable advcode editimage tableofcontents mergetags powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant"))
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}